# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addParticipantDialog.ui'
#
# Created: Fri Jan 29 21:50:38 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddParticipantDialog(object):
    def setupUi(self, AddParticipantDialog):
        AddParticipantDialog.setObjectName(_fromUtf8("AddParticipantDialog"))
        AddParticipantDialog.resize(492, 849)
        self.gridLayout = QtGui.QGridLayout(AddParticipantDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.firstNameLabel = QtGui.QLabel(AddParticipantDialog)
        self.firstNameLabel.setObjectName(_fromUtf8("firstNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(AddParticipantDialog)
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.parentLabel = QtGui.QLabel(AddParticipantDialog)
        self.parentLabel.setObjectName(_fromUtf8("parentLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.parentLabel)
        self.parentLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.parentLineEdit.setObjectName(_fromUtf8("parentLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.parentLineEdit)
        self.addressLabel = QtGui.QLabel(AddParticipantDialog)
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.addressLabel)
        self.addressLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.cityLabel = QtGui.QLabel(AddParticipantDialog)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.postalCodeLabel = QtGui.QLabel(AddParticipantDialog)
        self.postalCodeLabel.setObjectName(_fromUtf8("postalCodeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.postalCodeLabel)
        self.postalCodeLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.postalCodeLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.postalCodeLineEdit.setObjectName(_fromUtf8("postalCodeLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.postalCodeLineEdit)
        self.homePhoneLabel = QtGui.QLabel(AddParticipantDialog)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.homePhoneLabel)
        self.homePhoneLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.homePhoneLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.homePhoneLineEdit)
        self.cellPhoneLabel = QtGui.QLabel(AddParticipantDialog)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.cellPhoneLabel)
        self.cellPhoneLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.cellPhoneLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cellPhoneLineEdit)
        self.emailLabel = QtGui.QLabel(AddParticipantDialog)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.emailLineEdit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.dateOfBirthLabel = QtGui.QLabel(AddParticipantDialog)
        self.dateOfBirthLabel.setObjectName(_fromUtf8("dateOfBirthLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.dateOfBirthLabel)
        self.dateOfBirthDateEdit = QtGui.QDateEdit(AddParticipantDialog)
        self.dateOfBirthDateEdit.setAutoFillBackground(False)
        self.dateOfBirthDateEdit.setDate(QtCore.QDate(1996, 1, 1))
        self.dateOfBirthDateEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.dateOfBirthDateEdit.setCalendarPopup(True)
        self.dateOfBirthDateEdit.setObjectName(_fromUtf8("dateOfBirthDateEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.dateOfBirthDateEdit)
        self.ageLabel = QtGui.QLabel(AddParticipantDialog)
        self.ageLabel.setObjectName(_fromUtf8("ageLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.ageLabel)
        self.ageSpinBox = QtGui.QSpinBox(AddParticipantDialog)
        self.ageSpinBox.setMinimum(8)
        self.ageSpinBox.setObjectName(_fromUtf8("ageSpinBox"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.ageSpinBox)
        self.schoolAttendingLabel = QtGui.QLabel(AddParticipantDialog)
        self.schoolAttendingLabel.setObjectName(_fromUtf8("schoolAttendingLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.schoolAttendingLabel)
        self.schoolAttendingLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.schoolAttendingLineEdit.setObjectName(_fromUtf8("schoolAttendingLineEdit"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.schoolAttendingLineEdit)
        self.schoolGradeLabel = QtGui.QLabel(AddParticipantDialog)
        self.schoolGradeLabel.setObjectName(_fromUtf8("schoolGradeLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.schoolGradeLabel)
        self.schoolGradeLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.schoolGradeLineEdit.setObjectName(_fromUtf8("schoolGradeLineEdit"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.schoolGradeLineEdit)
        self.groupNameLabel = QtGui.QLabel(AddParticipantDialog)
        self.groupNameLabel.setObjectName(_fromUtf8("groupNameLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.groupNameLabel)
        self.groupSizeLabel = QtGui.QLabel(AddParticipantDialog)
        self.groupSizeLabel.setObjectName(_fromUtf8("groupSizeLabel"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.groupSizeLabel)
        self.groupSizeLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.groupSizeLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupSizeLineEdit.setObjectName(_fromUtf8("groupSizeLineEdit"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.groupSizeLineEdit)
        self.averageAgeLabel = QtGui.QLabel(AddParticipantDialog)
        self.averageAgeLabel.setObjectName(_fromUtf8("averageAgeLabel"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.averageAgeLabel)
        self.averageAgeLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.averageAgeLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.averageAgeLineEdit.setObjectName(_fromUtf8("averageAgeLineEdit"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.averageAgeLineEdit)
        self.contactPersonLabel = QtGui.QLabel(AddParticipantDialog)
        self.contactPersonLabel.setObjectName(_fromUtf8("contactPersonLabel"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.contactPersonLabel)
        self.contactPersonLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.contactPersonLineEdit.setEnabled(False)
        self.contactPersonLineEdit.setObjectName(_fromUtf8("contactPersonLineEdit"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.contactPersonLineEdit)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.clearContactBtn_2 = QtGui.QPushButton(AddParticipantDialog)
        self.clearContactBtn_2.setObjectName(_fromUtf8("clearContactBtn_2"))
        self.horizontalLayout_10.addWidget(self.clearContactBtn_2)
        self.chooseContactBtn_2 = QtGui.QPushButton(AddParticipantDialog)
        self.chooseContactBtn_2.setObjectName(_fromUtf8("chooseContactBtn_2"))
        self.horizontalLayout_10.addWidget(self.chooseContactBtn_2)
        self.createContactBtn_2 = QtGui.QPushButton(AddParticipantDialog)
        self.createContactBtn_2.setObjectName(_fromUtf8("createContactBtn_2"))
        self.horizontalLayout_10.addWidget(self.createContactBtn_2)
        self.formLayout.setLayout(17, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.timeConstraintsGroupBox = QtGui.QGroupBox(AddParticipantDialog)
        self.timeConstraintsGroupBox.setFlat(False)
        self.timeConstraintsGroupBox.setCheckable(True)
        self.timeConstraintsGroupBox.setChecked(False)
        self.timeConstraintsGroupBox.setObjectName(_fromUtf8("timeConstraintsGroupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.timeConstraintsGroupBox)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.earliestPerformanceTimeLabel_2 = QtGui.QLabel(self.timeConstraintsGroupBox)
        self.earliestPerformanceTimeLabel_2.setObjectName(_fromUtf8("earliestPerformanceTimeLabel_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.earliestPerformanceTimeLabel_2)
        self.earliestPerformanceTimeTimeEdit_2 = QtGui.QTimeEdit(self.timeConstraintsGroupBox)
        self.earliestPerformanceTimeTimeEdit_2.setTime(QtCore.QTime(9, 0, 0))
        self.earliestPerformanceTimeTimeEdit_2.setObjectName(_fromUtf8("earliestPerformanceTimeTimeEdit_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.earliestPerformanceTimeTimeEdit_2)
        self.latestPerformanceTimeLabel_2 = QtGui.QLabel(self.timeConstraintsGroupBox)
        self.latestPerformanceTimeLabel_2.setObjectName(_fromUtf8("latestPerformanceTimeLabel_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.latestPerformanceTimeLabel_2)
        self.latestPerformanceTimeTimeEdit_2 = QtGui.QTimeEdit(self.timeConstraintsGroupBox)
        self.latestPerformanceTimeTimeEdit_2.setTime(QtCore.QTime(15, 0, 0))
        self.latestPerformanceTimeTimeEdit_2.setObjectName(_fromUtf8("latestPerformanceTimeTimeEdit_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.latestPerformanceTimeTimeEdit_2)
        self.formLayout.setWidget(18, QtGui.QFormLayout.SpanningRole, self.timeConstraintsGroupBox)
        self.groupNameLineEdit = QtGui.QLineEdit(AddParticipantDialog)
        self.groupNameLineEdit.setObjectName(_fromUtf8("groupNameLineEdit"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.groupNameLineEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        self.participantTabWidget = QtGui.QTabWidget(AddParticipantDialog)
        self.participantTabWidget.setObjectName(_fromUtf8("participantTabWidget"))
        self.gridLayout.addWidget(self.participantTabWidget, 1, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(167, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(AddParticipantDialog)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(AddParticipantDialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)

        self.retranslateUi(AddParticipantDialog)
        self.participantTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AddParticipantDialog)

    def retranslateUi(self, AddParticipantDialog):
        AddParticipantDialog.setWindowTitle(_translate("AddParticipantDialog", "Dialog", None))
        self.firstNameLabel.setText(_translate("AddParticipantDialog", "First Name", None))
        self.lastNameLabel.setText(_translate("AddParticipantDialog", "Last Name", None))
        self.parentLabel.setText(_translate("AddParticipantDialog", "Parent", None))
        self.addressLabel.setText(_translate("AddParticipantDialog", "Address", None))
        self.cityLabel.setText(_translate("AddParticipantDialog", "City", None))
        self.postalCodeLabel.setText(_translate("AddParticipantDialog", "Postal Code", None))
        self.homePhoneLabel.setText(_translate("AddParticipantDialog", "Home Phone", None))
        self.cellPhoneLabel.setText(_translate("AddParticipantDialog", "Cell Phone", None))
        self.emailLabel.setText(_translate("AddParticipantDialog", "Email", None))
        self.dateOfBirthLabel.setText(_translate("AddParticipantDialog", "Date of Birth", None))
        self.dateOfBirthDateEdit.setDisplayFormat(_translate("AddParticipantDialog", "yyyy-MM-dd", None))
        self.ageLabel.setText(_translate("AddParticipantDialog", "Age as of Jan. 1 ", None))
        self.schoolAttendingLabel.setText(_translate("AddParticipantDialog", "School Currently Attending", None))
        self.schoolGradeLabel.setText(_translate("AddParticipantDialog", "School Grade", None))
        self.groupNameLabel.setText(_translate("AddParticipantDialog", "Group Name", None))
        self.groupSizeLabel.setText(_translate("AddParticipantDialog", "Number of Participants", None))
        self.averageAgeLabel.setText(_translate("AddParticipantDialog", "Average Age", None))
        self.contactPersonLabel.setText(_translate("AddParticipantDialog", "Contact Person", None))
        self.clearContactBtn_2.setText(_translate("AddParticipantDialog", "Clear", None))
        self.chooseContactBtn_2.setText(_translate("AddParticipantDialog", "Choose...", None))
        self.createContactBtn_2.setText(_translate("AddParticipantDialog", "Create New...", None))
        self.timeConstraintsGroupBox.setTitle(_translate("AddParticipantDialog", "Time Constraints", None))
        self.earliestPerformanceTimeLabel_2.setText(_translate("AddParticipantDialog", "Earliest Performance Time", None))
        self.latestPerformanceTimeLabel_2.setText(_translate("AddParticipantDialog", "Latest Performance Time", None))
        self.pushButton_2.setText(_translate("AddParticipantDialog", "&Cancel", None))
        self.pushButton.setText(_translate("AddParticipantDialog", "A&dd Participant", None))

