# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addEntryDialog.ui'
#
# Created: Tue Oct 21 00:24:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddEntryDialog(object):
    def setupUi(self, AddEntryDialog):
        AddEntryDialog.setObjectName(_fromUtf8("AddEntryDialog"))
        AddEntryDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AddEntryDialog.resize(546, 653)
        self.gridLayout = QtGui.QGridLayout(AddEntryDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addEntryBtn = QtGui.QPushButton(AddEntryDialog)
        self.addEntryBtn.setObjectName(_fromUtf8("addEntryBtn"))
        self.gridLayout.addWidget(self.addEntryBtn, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.cancelBtn = QtGui.QPushButton(AddEntryDialog)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.gridLayout.addWidget(self.cancelBtn, 1, 1, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.participantLabel = QtGui.QLabel(AddEntryDialog)
        self.participantLabel.setObjectName(_fromUtf8("participantLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.participantLabel)
        self.participantLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.participantLineEdit.setEnabled(False)
        self.participantLineEdit.setObjectName(_fromUtf8("participantLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.participantLineEdit)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chooseParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.chooseParticipantBtn.setEnabled(True)
        self.chooseParticipantBtn.setObjectName(_fromUtf8("chooseParticipantBtn"))
        self.gridLayout_2.addWidget(self.chooseParticipantBtn, 0, 0, 1, 1)
        self.createNewSoloParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewSoloParticipantBtn.setObjectName(_fromUtf8("createNewSoloParticipantBtn"))
        self.gridLayout_2.addWidget(self.createNewSoloParticipantBtn, 0, 1, 1, 1)
        self.createNewGroupParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewGroupParticipantBtn.setObjectName(_fromUtf8("createNewGroupParticipantBtn"))
        self.gridLayout_2.addWidget(self.createNewGroupParticipantBtn, 0, 2, 1, 1)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout_2)
        self.teacherLabel = QtGui.QLabel(AddEntryDialog)
        self.teacherLabel.setObjectName(_fromUtf8("teacherLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.teacherLabel)
        self.teacherLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.teacherLineEdit.setEnabled(False)
        self.teacherLineEdit.setObjectName(_fromUtf8("teacherLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.teacherLineEdit)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chooseTeacherBtn = QtGui.QPushButton(AddEntryDialog)
        self.chooseTeacherBtn.setEnabled(True)
        self.chooseTeacherBtn.setObjectName(_fromUtf8("chooseTeacherBtn"))
        self.gridLayout_3.addWidget(self.chooseTeacherBtn, 0, 0, 1, 1)
        self.createNewTeacherBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewTeacherBtn.setObjectName(_fromUtf8("createNewTeacherBtn"))
        self.gridLayout_3.addWidget(self.createNewTeacherBtn, 0, 1, 1, 1)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.gridLayout_3)
        self.disciplineLabel = QtGui.QLabel(AddEntryDialog)
        self.disciplineLabel.setObjectName(_fromUtf8("disciplineLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.disciplineLabel)
        self.disciplineComboBox = QtGui.QComboBox(AddEntryDialog)
        self.disciplineComboBox.setObjectName(_fromUtf8("disciplineComboBox"))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.disciplineComboBox)
        self.participantLevelGradeLabel = QtGui.QLabel(AddEntryDialog)
        self.participantLevelGradeLabel.setObjectName(_fromUtf8("participantLevelGradeLabel"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.participantLevelGradeLabel)
        self.levelLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.levelLineEdit.setObjectName(_fromUtf8("levelLineEdit"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.levelLineEdit)
        self.classNumberLabel = QtGui.QLabel(AddEntryDialog)
        self.classNumberLabel.setObjectName(_fromUtf8("classNumberLabel"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.classNumberLabel)
        self.classNumberLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.classNumberLineEdit.setObjectName(_fromUtf8("classNumberLineEdit"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.classNumberLineEdit)
        self.classNameLabel = QtGui.QLabel(AddEntryDialog)
        self.classNameLabel.setObjectName(_fromUtf8("classNameLabel"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.classNameLabel)
        self.classNameLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.classNameLineEdit.setObjectName(_fromUtf8("classNameLineEdit"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.classNameLineEdit)
        self.styleLabel = QtGui.QLabel(AddEntryDialog)
        self.styleLabel.setObjectName(_fromUtf8("styleLabel"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.styleLabel)
        self.styleLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.styleLineEdit.setObjectName(_fromUtf8("styleLineEdit"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.styleLineEdit)
        self.instrumentLabel = QtGui.QLabel(AddEntryDialog)
        self.instrumentLabel.setObjectName(_fromUtf8("instrumentLabel"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.instrumentLabel)
        self.instrumentLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.instrumentLineEdit.setObjectName(_fromUtf8("instrumentLineEdit"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.instrumentLineEdit)
        self.titleLabel = QtGui.QLabel(AddEntryDialog)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.titleLabel)
        self.titleLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.titleLineEdit.setObjectName(_fromUtf8("titleLineEdit"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.titleLineEdit)
        self.composerLabel = QtGui.QLabel(AddEntryDialog)
        self.composerLabel.setObjectName(_fromUtf8("composerLabel"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.composerLabel)
        self.composerLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.composerLineEdit.setObjectName(_fromUtf8("composerLineEdit"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.composerLineEdit)
        self.arrangerLabel = QtGui.QLabel(AddEntryDialog)
        self.arrangerLabel.setObjectName(_fromUtf8("arrangerLabel"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.LabelRole, self.arrangerLabel)
        self.arrangerLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.arrangerLineEdit.setObjectName(_fromUtf8("arrangerLineEdit"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.FieldRole, self.arrangerLineEdit)
        self.artistLabel = QtGui.QLabel(AddEntryDialog)
        self.artistLabel.setObjectName(_fromUtf8("artistLabel"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.artistLabel)
        self.artistLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.artistLineEdit.setObjectName(_fromUtf8("artistLineEdit"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.artistLineEdit)
        self.authorLabel = QtGui.QLabel(AddEntryDialog)
        self.authorLabel.setObjectName(_fromUtf8("authorLabel"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.LabelRole, self.authorLabel)
        self.authorLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.authorLineEdit.setObjectName(_fromUtf8("authorLineEdit"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.FieldRole, self.authorLineEdit)
        self.opusLabel = QtGui.QLabel(AddEntryDialog)
        self.opusLabel.setObjectName(_fromUtf8("opusLabel"))
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.LabelRole, self.opusLabel)
        self.opusLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.opusLineEdit.setObjectName(_fromUtf8("opusLineEdit"))
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.FieldRole, self.opusLineEdit)
        self.noLabel = QtGui.QLabel(AddEntryDialog)
        self.noLabel.setObjectName(_fromUtf8("noLabel"))
        self.formLayout_2.setWidget(17, QtGui.QFormLayout.LabelRole, self.noLabel)
        self.noLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.noLineEdit.setObjectName(_fromUtf8("noLineEdit"))
        self.formLayout_2.setWidget(17, QtGui.QFormLayout.FieldRole, self.noLineEdit)
        self.movementLabel = QtGui.QLabel(AddEntryDialog)
        self.movementLabel.setObjectName(_fromUtf8("movementLabel"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.LabelRole, self.movementLabel)
        self.movementLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.movementLineEdit.setObjectName(_fromUtf8("movementLineEdit"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.FieldRole, self.movementLineEdit)
        self.performanceTimeLabel = QtGui.QLabel(AddEntryDialog)
        self.performanceTimeLabel.setObjectName(_fromUtf8("performanceTimeLabel"))
        self.formLayout_2.setWidget(19, QtGui.QFormLayout.LabelRole, self.performanceTimeLabel)
        self.performanceTimeEdit = QtGui.QTimeEdit(AddEntryDialog)
        self.performanceTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 59, 59)))
        self.performanceTimeEdit.setObjectName(_fromUtf8("performanceTimeEdit"))
        self.formLayout_2.setWidget(19, QtGui.QFormLayout.FieldRole, self.performanceTimeEdit)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 3)

        self.retranslateUi(AddEntryDialog)
        QtCore.QMetaObject.connectSlotsByName(AddEntryDialog)

    def retranslateUi(self, AddEntryDialog):
        AddEntryDialog.setWindowTitle(_translate("AddEntryDialog", "Add Entry", None))
        self.addEntryBtn.setText(_translate("AddEntryDialog", "A&dd Entry", None))
        self.cancelBtn.setText(_translate("AddEntryDialog", "&Cancel", None))
        self.participantLabel.setText(_translate("AddEntryDialog", "Participant", None))
        self.chooseParticipantBtn.setToolTip(_translate("AddEntryDialog", "TODO", None))
        self.chooseParticipantBtn.setText(_translate("AddEntryDialog", "Choose...", None))
        self.createNewSoloParticipantBtn.setText(_translate("AddEntryDialog", "Create New &Solo...", None))
        self.createNewGroupParticipantBtn.setText(_translate("AddEntryDialog", "Create New &Group...", None))
        self.teacherLabel.setText(_translate("AddEntryDialog", "Teacher", None))
        self.chooseTeacherBtn.setText(_translate("AddEntryDialog", "Choose...", None))
        self.createNewTeacherBtn.setText(_translate("AddEntryDialog", "Create New...", None))
        self.disciplineLabel.setText(_translate("AddEntryDialog", "Discipline", None))
        self.disciplineComboBox.setItemText(0, _translate("AddEntryDialog", "Dance", None))
        self.disciplineComboBox.setItemText(1, _translate("AddEntryDialog", "Piano", None))
        self.disciplineComboBox.setItemText(2, _translate("AddEntryDialog", "Choral", None))
        self.disciplineComboBox.setItemText(3, _translate("AddEntryDialog", "Vocal", None))
        self.disciplineComboBox.setItemText(4, _translate("AddEntryDialog", "Instrumental", None))
        self.disciplineComboBox.setItemText(5, _translate("AddEntryDialog", "Band", None))
        self.disciplineComboBox.setItemText(6, _translate("AddEntryDialog", "Speech", None))
        self.participantLevelGradeLabel.setText(_translate("AddEntryDialog", "Level/Years of Instruction", None))
        self.classNumberLabel.setText(_translate("AddEntryDialog", "Class Number", None))
        self.classNameLabel.setText(_translate("AddEntryDialog", "Class Name", None))
        self.styleLabel.setText(_translate("AddEntryDialog", "Style", None))
        self.instrumentLabel.setText(_translate("AddEntryDialog", "Instrument", None))
        self.titleLabel.setText(_translate("AddEntryDialog", "Title", None))
        self.composerLabel.setText(_translate("AddEntryDialog", "Composer", None))
        self.arrangerLabel.setText(_translate("AddEntryDialog", "Arranger", None))
        self.artistLabel.setText(_translate("AddEntryDialog", "Artist", None))
        self.authorLabel.setText(_translate("AddEntryDialog", "Author", None))
        self.opusLabel.setText(_translate("AddEntryDialog", "Opus", None))
        self.noLabel.setText(_translate("AddEntryDialog", "No.", None))
        self.movementLabel.setText(_translate("AddEntryDialog", "Movement", None))
        self.performanceTimeLabel.setText(_translate("AddEntryDialog", "Performance Time (mm:ss)", None))
        self.performanceTimeEdit.setDisplayFormat(_translate("AddEntryDialog", "mm:ss", None))

