# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addEntryDialog.ui'
#
# Created: Sun Dec  7 17:21:56 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddEntryDialog(object):
    def setupUi(self, AddEntryDialog):
        AddEntryDialog.setObjectName(_fromUtf8("AddEntryDialog"))
        AddEntryDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AddEntryDialog.resize(546, 508)
        self.gridLayout = QtGui.QGridLayout(AddEntryDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.participantLabel = QtGui.QLabel(AddEntryDialog)
        self.participantLabel.setObjectName(_fromUtf8("participantLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.participantLabel)
        self.participantLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.participantLineEdit.setEnabled(False)
        self.participantLineEdit.setObjectName(_fromUtf8("participantLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.participantLineEdit)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chooseParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.chooseParticipantBtn.setEnabled(True)
        self.chooseParticipantBtn.setToolTip(_fromUtf8(""))
        self.chooseParticipantBtn.setObjectName(_fromUtf8("chooseParticipantBtn"))
        self.gridLayout_2.addWidget(self.chooseParticipantBtn, 0, 0, 1, 1)
        self.createNewSoloParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewSoloParticipantBtn.setObjectName(_fromUtf8("createNewSoloParticipantBtn"))
        self.gridLayout_2.addWidget(self.createNewSoloParticipantBtn, 0, 1, 1, 1)
        self.createNewGroupParticipantBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewGroupParticipantBtn.setObjectName(_fromUtf8("createNewGroupParticipantBtn"))
        self.gridLayout_2.addWidget(self.createNewGroupParticipantBtn, 0, 2, 1, 1)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout_2)
        self.teacherLabel = QtGui.QLabel(AddEntryDialog)
        self.teacherLabel.setObjectName(_fromUtf8("teacherLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.teacherLabel)
        self.teacherLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.teacherLineEdit.setEnabled(False)
        self.teacherLineEdit.setObjectName(_fromUtf8("teacherLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.teacherLineEdit)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chooseTeacherBtn = QtGui.QPushButton(AddEntryDialog)
        self.chooseTeacherBtn.setEnabled(True)
        self.chooseTeacherBtn.setObjectName(_fromUtf8("chooseTeacherBtn"))
        self.gridLayout_3.addWidget(self.chooseTeacherBtn, 0, 0, 1, 1)
        self.createNewTeacherBtn = QtGui.QPushButton(AddEntryDialog)
        self.createNewTeacherBtn.setObjectName(_fromUtf8("createNewTeacherBtn"))
        self.gridLayout_3.addWidget(self.createNewTeacherBtn, 0, 1, 1, 1)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.gridLayout_3)
        self.disciplineLabel = QtGui.QLabel(AddEntryDialog)
        self.disciplineLabel.setObjectName(_fromUtf8("disciplineLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.disciplineLabel)
        self.disciplineComboBox = QtGui.QComboBox(AddEntryDialog)
        self.disciplineComboBox.setObjectName(_fromUtf8("disciplineComboBox"))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.disciplineComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.disciplineComboBox)
        self.styleLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.styleLineEdit.setObjectName(_fromUtf8("styleLineEdit"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.FieldRole, self.styleLineEdit)
        self.levelLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.levelLineEdit.setObjectName(_fromUtf8("levelLineEdit"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.levelLineEdit)
        self.classNumberLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.classNumberLineEdit.setObjectName(_fromUtf8("classNumberLineEdit"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.classNumberLineEdit)
        self.classNumberLabel = QtGui.QLabel(AddEntryDialog)
        self.classNumberLabel.setObjectName(_fromUtf8("classNumberLabel"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.classNumberLabel)
        self.instrumentLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.instrumentLineEdit.setObjectName(_fromUtf8("instrumentLineEdit"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.instrumentLineEdit)
        self.styleLabel = QtGui.QLabel(AddEntryDialog)
        self.styleLabel.setObjectName(_fromUtf8("styleLabel"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.LabelRole, self.styleLabel)
        self.participantLevelGradeLabel = QtGui.QLabel(AddEntryDialog)
        self.participantLevelGradeLabel.setObjectName(_fromUtf8("participantLevelGradeLabel"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.participantLevelGradeLabel)
        self.instrumentLabel = QtGui.QLabel(AddEntryDialog)
        self.instrumentLabel.setObjectName(_fromUtf8("instrumentLabel"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.instrumentLabel)
        self.classNameLineEdit = QtGui.QLineEdit(AddEntryDialog)
        self.classNameLineEdit.setObjectName(_fromUtf8("classNameLineEdit"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.classNameLineEdit)
        self.classNameLabel = QtGui.QLabel(AddEntryDialog)
        self.classNameLabel.setObjectName(_fromUtf8("classNameLabel"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.classNameLabel)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(AddEntryDialog)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabWidgetPage1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = PieceWidget(self.tabWidgetPage1)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 4)
        self.addPieceBtn = QtGui.QPushButton(AddEntryDialog)
        self.addPieceBtn.setObjectName(_fromUtf8("addPieceBtn"))
        self.gridLayout.addWidget(self.addPieceBtn, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.cancelBtn = QtGui.QPushButton(AddEntryDialog)
        self.cancelBtn.setAutoDefault(False)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.gridLayout.addWidget(self.cancelBtn, 3, 2, 1, 1)
        self.addEntryBtn = QtGui.QPushButton(AddEntryDialog)
        self.addEntryBtn.setAutoDefault(False)
        self.addEntryBtn.setDefault(True)
        self.addEntryBtn.setObjectName(_fromUtf8("addEntryBtn"))
        self.gridLayout.addWidget(self.addEntryBtn, 3, 3, 1, 1)

        self.retranslateUi(AddEntryDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddEntryDialog)
        AddEntryDialog.setTabOrder(self.chooseParticipantBtn, self.createNewSoloParticipantBtn)
        AddEntryDialog.setTabOrder(self.createNewSoloParticipantBtn, self.createNewGroupParticipantBtn)
        AddEntryDialog.setTabOrder(self.createNewGroupParticipantBtn, self.chooseTeacherBtn)
        AddEntryDialog.setTabOrder(self.chooseTeacherBtn, self.createNewTeacherBtn)
        AddEntryDialog.setTabOrder(self.createNewTeacherBtn, self.disciplineComboBox)
        AddEntryDialog.setTabOrder(self.disciplineComboBox, self.classNumberLineEdit)
        AddEntryDialog.setTabOrder(self.classNumberLineEdit, self.classNameLineEdit)
        AddEntryDialog.setTabOrder(self.classNameLineEdit, self.levelLineEdit)
        AddEntryDialog.setTabOrder(self.levelLineEdit, self.instrumentLineEdit)
        AddEntryDialog.setTabOrder(self.instrumentLineEdit, self.styleLineEdit)
        AddEntryDialog.setTabOrder(self.styleLineEdit, self.tabWidget)
        AddEntryDialog.setTabOrder(self.tabWidget, self.addPieceBtn)
        AddEntryDialog.setTabOrder(self.addPieceBtn, self.cancelBtn)
        AddEntryDialog.setTabOrder(self.cancelBtn, self.addEntryBtn)
        AddEntryDialog.setTabOrder(self.addEntryBtn, self.teacherLineEdit)
        AddEntryDialog.setTabOrder(self.teacherLineEdit, self.participantLineEdit)

    def retranslateUi(self, AddEntryDialog):
        AddEntryDialog.setWindowTitle(_translate("AddEntryDialog", "Add Entry", None))
        self.participantLabel.setText(_translate("AddEntryDialog", "Participant", None))
        self.chooseParticipantBtn.setText(_translate("AddEntryDialog", "Choose...", None))
        self.createNewSoloParticipantBtn.setText(_translate("AddEntryDialog", "Create New &Solo...", None))
        self.createNewGroupParticipantBtn.setText(_translate("AddEntryDialog", "Create New &Group...", None))
        self.teacherLabel.setText(_translate("AddEntryDialog", "Teacher", None))
        self.chooseTeacherBtn.setText(_translate("AddEntryDialog", "Choose...", None))
        self.createNewTeacherBtn.setText(_translate("AddEntryDialog", "Create New...", None))
        self.disciplineLabel.setText(_translate("AddEntryDialog", "Discipline", None))
        self.disciplineComboBox.setItemText(0, _translate("AddEntryDialog", "Dance", None))
        self.disciplineComboBox.setItemText(1, _translate("AddEntryDialog", "Piano", None))
        self.disciplineComboBox.setItemText(2, _translate("AddEntryDialog", "Choral", None))
        self.disciplineComboBox.setItemText(3, _translate("AddEntryDialog", "Vocal", None))
        self.disciplineComboBox.setItemText(4, _translate("AddEntryDialog", "Instrumental", None))
        self.disciplineComboBox.setItemText(5, _translate("AddEntryDialog", "Band", None))
        self.disciplineComboBox.setItemText(6, _translate("AddEntryDialog", "Speech", None))
        self.classNumberLabel.setText(_translate("AddEntryDialog", "Class Number", None))
        self.styleLabel.setText(_translate("AddEntryDialog", "Style", None))
        self.participantLevelGradeLabel.setText(_translate("AddEntryDialog", "Level/Years of Instruction", None))
        self.instrumentLabel.setText(_translate("AddEntryDialog", "Instrument", None))
        self.classNameLabel.setText(_translate("AddEntryDialog", "Class Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("AddEntryDialog", "Piece 1", None))
        self.addPieceBtn.setText(_translate("AddEntryDialog", "Add &Piece", None))
        self.cancelBtn.setText(_translate("AddEntryDialog", "&Cancel", None))
        self.addEntryBtn.setText(_translate("AddEntryDialog", "A&dd Entry", None))

from pieceWidget import PieceWidget
