# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Tue Feb  2 21:22:33 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1370, 777)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.participantTableView = QtGui.QTableView(self.centralwidget)
        self.participantTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.participantTableView.setAlternatingRowColors(True)
        self.participantTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.participantTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.participantTableView.setSortingEnabled(True)
        self.participantTableView.setObjectName(_fromUtf8("participantTableView"))
        self.participantTableView.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.participantTableView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addParticipantBtn = QtGui.QPushButton(self.centralwidget)
        self.addParticipantBtn.setObjectName(_fromUtf8("addParticipantBtn"))
        self.horizontalLayout.addWidget(self.addParticipantBtn)
        self.editParticipantBtn = QtGui.QPushButton(self.centralwidget)
        self.editParticipantBtn.setObjectName(_fromUtf8("editParticipantBtn"))
        self.horizontalLayout.addWidget(self.editParticipantBtn)
        self.deleteParticipantBtn = QtGui.QPushButton(self.centralwidget)
        self.deleteParticipantBtn.setObjectName(_fromUtf8("deleteParticipantBtn"))
        self.horizontalLayout.addWidget(self.deleteParticipantBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.teacherTableView = QtGui.QTableView(self.centralwidget)
        self.teacherTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.teacherTableView.setAlternatingRowColors(True)
        self.teacherTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.teacherTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.teacherTableView.setSortingEnabled(True)
        self.teacherTableView.setObjectName(_fromUtf8("teacherTableView"))
        self.verticalLayout_2.addWidget(self.teacherTableView)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.addTeacherBtn = QtGui.QPushButton(self.centralwidget)
        self.addTeacherBtn.setObjectName(_fromUtf8("addTeacherBtn"))
        self.horizontalLayout_4.addWidget(self.addTeacherBtn)
        self.editTeacherBtn = QtGui.QPushButton(self.centralwidget)
        self.editTeacherBtn.setObjectName(_fromUtf8("editTeacherBtn"))
        self.horizontalLayout_4.addWidget(self.editTeacherBtn)
        self.deleteTeacherBtn = QtGui.QPushButton(self.centralwidget)
        self.deleteTeacherBtn.setObjectName(_fromUtf8("deleteTeacherBtn"))
        self.horizontalLayout_4.addWidget(self.deleteTeacherBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.splitter_2)
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.entryTableView = QtGui.QTableView(self.verticalLayoutWidget_4)
        self.entryTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.entryTableView.setAlternatingRowColors(True)
        self.entryTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.entryTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.entryTableView.setSortingEnabled(True)
        self.entryTableView.setObjectName(_fromUtf8("entryTableView"))
        self.verticalLayout_4.addWidget(self.entryTableView)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.addEntryBtn = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.addEntryBtn.setObjectName(_fromUtf8("addEntryBtn"))
        self.horizontalLayout_3.addWidget(self.addEntryBtn)
        self.editEntryBtn = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.editEntryBtn.setObjectName(_fromUtf8("editEntryBtn"))
        self.horizontalLayout_3.addWidget(self.editEntryBtn)
        self.deleteEntryBtn = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.deleteEntryBtn.setObjectName(_fromUtf8("deleteEntryBtn"))
        self.horizontalLayout_3.addWidget(self.deleteEntryBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.splitter_2)
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.pieceTableView = QtGui.QTableView(self.verticalLayoutWidget_3)
        self.pieceTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.pieceTableView.setAlternatingRowColors(True)
        self.pieceTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pieceTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pieceTableView.setSortingEnabled(True)
        self.pieceTableView.setObjectName(_fromUtf8("pieceTableView"))
        self.verticalLayout_3.addWidget(self.pieceTableView)
        self.gridLayout.addWidget(self.splitter_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Schedule = QtGui.QMenu(self.menubar)
        self.menu_Schedule.setObjectName(_fromUtf8("menu_Schedule"))
        self.menu_Database = QtGui.QMenu(self.menubar)
        self.menu_Database.setObjectName(_fromUtf8("menu_Database"))
        MainWindow.setMenuBar(self.menubar)
        self.createBackupAction = QtGui.QAction(MainWindow)
        self.createBackupAction.setObjectName(_fromUtf8("createBackupAction"))
        self.action_Load_Backup = QtGui.QAction(MainWindow)
        self.action_Load_Backup.setObjectName(_fromUtf8("action_Load_Backup"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.runSchedulerAction = QtGui.QAction(MainWindow)
        self.runSchedulerAction.setObjectName(_fromUtf8("runSchedulerAction"))
        self.exportAction = QtGui.QAction(MainWindow)
        self.exportAction.setObjectName(_fromUtf8("exportAction"))
        self.menu_File.addAction(self.exitAction)
        self.menu_Schedule.addAction(self.runSchedulerAction)
        self.menu_Database.addAction(self.createBackupAction)
        self.menu_Database.addAction(self.exportAction)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Schedule.menuAction())
        self.menubar.addAction(self.menu_Database.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Arts Festival Organizer", None))
        self.label_2.setText(_translate("MainWindow", "Participants", None))
        self.addParticipantBtn.setText(_translate("MainWindow", "Add New Participant", None))
        self.editParticipantBtn.setText(_translate("MainWindow", "Edit Participant", None))
        self.deleteParticipantBtn.setText(_translate("MainWindow", "Delete Participant", None))
        self.label_3.setText(_translate("MainWindow", "Teachers", None))
        self.addTeacherBtn.setText(_translate("MainWindow", "Add New Teacher", None))
        self.editTeacherBtn.setText(_translate("MainWindow", "Edit Teacher", None))
        self.deleteTeacherBtn.setText(_translate("MainWindow", "Delete Teacher", None))
        self.label_4.setText(_translate("MainWindow", "Entries", None))
        self.addEntryBtn.setText(_translate("MainWindow", "Add New Entry", None))
        self.editEntryBtn.setText(_translate("MainWindow", "Edit Entry", None))
        self.deleteEntryBtn.setText(_translate("MainWindow", "Delete Entry", None))
        self.label.setText(_translate("MainWindow", "Pieces", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Schedule.setTitle(_translate("MainWindow", "&Schedule", None))
        self.menu_Database.setTitle(_translate("MainWindow", "&Database", None))
        self.createBackupAction.setText(_translate("MainWindow", "&Create Backup", None))
        self.action_Load_Backup.setText(_translate("MainWindow", "&Load Backup", None))
        self.exitAction.setText(_translate("MainWindow", "E&xit", None))
        self.runSchedulerAction.setText(_translate("MainWindow", "Run Scheduler...", None))
        self.exportAction.setText(_translate("MainWindow", "Export to CSV", None))

